/*
//Name: GamePanel.java                            //
//Date Created: 11/20/21                          //
//Description: This is the class for the GamePanel//
*/

//Last Edited: Luke Jodice (12/5/21)
package edu.endicott.ltcj.gui;

/**
 *
 * @author jodic
 */
public class GamePanel extends javax.swing.JPanel {
     private String displayText;
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();
    }

    protected void setDisplayText(String s){
       
   }
   
   /**
    * Action for when the close button is pressed
    */
   protected void startButtonPressed(){
       
   }
   
   /**
    * Action for when the close button is pressed
    */
   protected void closeButtonPressed(){
       
   }
   
   /**
    * Changes the panel to prompt the start screen to be launched making it visible
    */
   public void launchStartScreen(){
       
   }
   
   /**
    * Changes the panel to prompt the end screen to be launched making it visible
    */
   public void launchEndScreen(){
   
   }
   
   /**
    * Changes the panel to the prompt to get the user's name
    */
   public void launchNameScreen(){
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
