// Name: LevelPanel.java                   //
// Date Created: 11/28/21		   //
// Description: Level panel GUI class      //

// Last Edited: Teddy Blazejowski (12/7/21)

package edu.endicott.ltcj.gui;

//import edu.endicott.ltcj.models.Level;

/**
 * GUI for level
 * 
 * @author teddyblazejowski
 */
public class LevelPanel extends javax.swing.JPanel {
    
//    private Level level;

    /**
     * Creates new form LevelPanel
     */
    public LevelPanel() {
        initComponents();
    }
    
    /**
     * Creates new form LevelPanel with level model
     * @param level Level instance
     */
//    public LevelPanel(Level level) {
//        this();
//        this.level = level;
//    }
    
    /**
     * Shows the start text on screen
     */
    public void displayStartScreen() {
        jlText.setVisible(true);
//        jlText.setText(level.getStartText());
    }
    
    /**
     * Shows the end text on screen
     */
    public void displayEndScreen() {
        jlText.setVisible(true);
//        jlText.setText(level.getEndText());
    }
    
    /**
     * Makes the text hidden from the screen
     */
    public void hideText() {
        jlText.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbNextLevel = new javax.swing.JButton();
        jbStartLevel = new javax.swing.JButton();
        jlText = new javax.swing.JLabel();

        jbNextLevel.setText("Next Level");
        jbNextLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextLevelActionPerformed(evt);
            }
        });

        jbStartLevel.setText("Start Level");
        jbStartLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartLevelActionPerformed(evt);
            }
        });

        jlText.setText("START/END TEXT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbStartLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(jbNextLevel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlText)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNextLevel)
                    .addComponent(jbStartLevel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Called when next level button is clicked
     * 
     * @param evt ActionEvent object
     */
    private void jbNextLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNextLevelActionPerformed

    /**
     * Called when start level button is clicked
     * 
     * @param evt ActionEvent object
     */
    private void jbStartLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbStartLevelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbNextLevel;
    private javax.swing.JButton jbStartLevel;
    private javax.swing.JLabel jlText;
    // End of variables declaration//GEN-END:variables
}
